### PR TITLE
Load correct URLs

### PR DESCRIPTION
**Pull request by AmazingMech2418**

### CODE REVIEW

**Comment by AmazingMech2418** [comment]
Note: This was never fixed.

**Comment by AmazingMech2418** [comment]
@MegaCode18 This is the same as the previous PR, but it was never fixed.

**Comment by radioblahaj** [comment]
I'm sorry @amazinigmech2418 , But this will be implanted by ourselves soon, We are fixing the travis build and more. So This will have to be on standby.

**Comment by AmazingMech2418** [comment]
@Narulacodes Travis isn't even needed to be honest. Can't you just delete it since it's just a style checker? This PR is needed because it will fix the 404 error in the editor.

**Comment by radioblahaj** [comment]
I would like to Merge this but, @MegaCode18  Declined your lastn Pr on this. We Hope to implant this soon.
 Travis is important for deploying, and etc. We use node and need travis.

**Comment by AmazingMech2418** [comment]
He declined my last PR because he didn't know this fixed it.

**Comment by AmazingMech2418** [comment]
REMOVE THE DUPLICATE AND INVALID TAGS SINCE THIS ISN'T EITHER OF THEM AND THIS WILL FIX IT IF YOU JUST MERGE IT!

**Comment by radioblahaj** [comment]
Well, I asigned it to him. 
He'll Get back to you.
I can't approve this

**Comment by AmazingMech2418** [comment]
You CAN. This is way more important than you think it is. THIS IS THE WHOLE PREVIEW WE'RE TALKING ABOUT!

**Comment by radioblahaj** [comment]
Ok. Fine.

**Comment by radioblahaj** [comment]
This Pr,Will Merge travis errors in merge develop into develop

**Comment by AmazingMech2418** [comment]
There are no travis errors.

**Comment by MattTheNub** [comment]
I mentioned already, not only is this fixed, it breaks other clones. NOT MERGING.

**Comment by MattTheNub** [comment]
Also, this probably won't be the preview in the future, as we will most likely be using the `/player` submodule @amazinigmech2418

**Comment by MattTheNub** [comment]
Also, Travis is...
1. Used for deploying to `gh-pages`
2. A way of testing that you didn't accidentally **BREAK THE ENTIRE PROJECT**

**Comment by AmazingMech2418** [comment]
It actually isn't fixed. Go to https://elementnet.js.org/elementnet-editor/app/views/editorView.html

**Comment by MattTheNub** [comment]
@amazinigmech2418 That's... not the built file
The *actual* file you want to see (the one that was built) is <https://elementnet.js.org/elementnet-editor/> (`index.html`)

**Comment by MattTheNub** [comment]
That's also why you don't get any CSS or JavaScript on the page you mentioned

**Comment by AmazingMech2418** [comment]
OK.

**Comment by MattTheNub** [comment]
Sorry for the misunderstanding

**Pull request closed without merging**
