### PR TITLE
Fix preview

### PR DESCRIPTION
**Pull request by MattTheNub**
Preview isn't in the root, rather in the current dir

### CODE REVIEW

**Review by radioblahaj — APPROVED** [review]

**Comment by AmazingMech2418** [comment]
@Narulacodes @MegaCode18 This doesn't work. It only adds a "." to it.

**Comment by radioblahaj** [comment]
We Have Fixed this in Other Pr to fix travis

**Comment by MattTheNub** [comment]
@amazinigmech2418 The `.` means relative to current directory, rather than root directory

**Comment by AmazingMech2418** [comment]
Actually, that is `..`.

**Comment by MattTheNub** [comment]
@amazinigmech2418 `..` is parent directory

**Pull request merged**
