### PR TITLE
Try to fix the build

### LINKED ISSUE #8: The Gh-pages Branch Needs A Makeover

### PR DESCRIPTION
**Pull request by MattTheNub**
Resolves #8

### CODE REVIEW

**Comment by radioblahaj** [comment]
Whats Wrong now?

**Review by radioblahaj — COMMENTED** [review]
Before I Approve this, Any Mistakes, You want to go over?

**Comment by MattTheNub** [comment]
Yes, the postinstall script doesn't seem to run (still)

**Review by MattTheNub — COMMENTED** [review]
The build seems to work properly. awaiting review from @elementnet/editor or @Narulacodes.

**Review by radioblahaj — COMMENTED** [review]
PRGTM

**Review by radioblahaj — APPROVED** [review]
Approved!

**Pull request merged**
