### PR TITLE
Fix Commits And Issue 2

### LINKED ISSUE #2: Add GH Pages for viewing

### PR DESCRIPTION
**Pull request by MattTheNub**
Mainly for gh-pages deployment
Resolves #2

### CODE REVIEW

**Comment by radioblahaj** [comment]
Can I review/?

**Comment by MattTheNub** [comment]
@narulacodes sure

**Review by radioblahaj — APPROVED** [review]
LGTM.
PRGTM

**Comment by radioblahaj** [comment]
I'm not autohirted to merge this, can i get the acces?

**Comment by radioblahaj** [comment]
Why Can't i Get Acces?

**Comment by MattTheNub** [comment]
You do...

**Pull request merged**
